# docker로 빌드할 이미지를 설정
FROM node:alpine as build

# 작업경로 및 디렉토리 설정
WORKDIR /Fems-Project/frontend

# 디폴트 리소스 경로에 있는 Package.json파일을 디렉토리 경로로 복사
COPY package*.json ./

# 웹앱의 구동, 빌드
RUN npm install

# 현재 작업상황 복사
COPY . .

# 빌드 시작
RUN npm run build

# docker에 nginx 이미지 설정
FROM nginx:1.16.0-alpine

# 맨위의 as build로부터 복사한다는 것을 선언한다.
COPY --from=build /Fems-Project/frontend/build /usr/share/nginx/html

# nginx 기본설정을 삭제한다
RUN rm /etc/nginx/conf.d/default.conf

# 리소스 경로에 있는 conf폴더를 도커의 폴더로 복사한다
COPY ./nginx/nginx.conf /etc/nginx/conf.d

# 80포트 오픈하고 nginx실행
EXPOSE 80

# ubuntu에서 nginx를 포어그라운드에서 실행할 경우 아래와 같이 실행한다.
CMD ["nginx", "-g","daemon off;"]