# 파이썬 버전 
FROM python:3.10-slim-bullseye

# 실행할 디렉토리
WORKDIR /Fems-Project/Backend

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONBUFFERED 1

COPY ./requirements.txt .

# 패키지 다운로드
RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

EXPOSE 8000

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
