# -*- coding: utf-8 -*-
"""전처리.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iopaZrhbAKlci-ZhBK1gMP3DV64KFv5Y
"""

import pandas as pd
from pandas import DataFrame
from pandas import Series
import numpy as np
# from google.colab import files
import io

df_inv = pd.read_csv('/home/jovyan/aaaa/raw_wminvdataall.csv')
df_inv

df_inv['run_datetime'] = df_inv['run_datetime']//10000

df_inv.info()

df_inv = df_inv.rename(columns={'run_datetime':'LpDate'})
df_inv

df_inv = df_inv.drop({'data_id', 'inv_alram'}, axis = 'columns')
df_inv

df_inv['inv_id'] = df_inv['inv_id'].replace(['I00', 'I01', 'I02', 'I03', 'I04', 'I05', 'I06', 'I07', 'I08', 'I09', 'I10', 'I11', 'I12', 'I13', 'I14', 'I15', 'I16', 'I17', 'I18', 'I19', 'I20'], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,17, 18, 19, 20])
df_inv

df_inv_1 = pd.DataFrame(data = df_inv['inv_id'] >= 11, columns=df_inv.columns)
df_inv_1

data = df_inv['inv_id'] >= 11
data

df_inv.info()

df_inv = df_inv.sort_values(by='inv_id',ascending=True)
df_inv

df_inv = df_inv.reset_index(drop=True)
df_inv

df_inv_1 = df_inv[0:2062631]
df_inv_1

df_inv_20 = df_inv[3437719:]
df_inv_20

df_inv_a = pd.merge(df_inv_1, df_inv_20, how='outer')

df_inv_a

df_inv_a['inv_A'] = df_inv_a['inv_A'] * 380

df_inv_a

df_inv_12 = df_inv[2062631:3437719]
df_inv_12

df_inv_12['inv_A'] = df_inv_12['inv_A'] * 220
df_inv_12

df_inv_all = pd.merge(df_inv_a, df_inv_12, how='outer')
df_inv_all

df_inv_all = df_inv_all.sort_values(['inv_id'], ignore_index=True)
df_inv_all

df_inv_all = df_inv_all.sort_values(['LpDate'], ignore_index=True)
df_inv_all

df_inv_all = df_inv_all.sort_values(['inv_id', 'LpDate'], ignore_index=True)
df_inv_all

df_inv_all['inv_A'] = df_inv_all['inv_A']/1000

# df_inv_all.to_csv('/home/jovyan/aaaa/df_inv_all.csv')

3609605/420

7296*12*21

df_inv_all.head(50)

df_15min = df_inv_all.groupby('LpDate').agg({'LpDate':max, 'inv_id':sum, 'inv_A':sum, 'inv_set_freq':'mean', 'inv_cur_freq':'mean', 'inv_run_state':sum})
df_15min

df_15min = df_15min.reset_index(drop=True)

df_15min

df_15min = df_15min.reset_index()

df_15min

print(df_15min.loc[df_15min['LpDate'] == 20210131001500])

print(df_15min.loc[df_15min['LpDate'] == 20221025093000])

df_15min = df_15min[455: 171878]

df_15min = df_15min.reset_index()

df_15min

df_15min = df_15min.drop('index', axis = 'columns')

df_15min

df_15min = df_15min.drop('level_0', axis = 'columns')
df_15min

df_15min

df_15min = df_15min[1:]
df_15min

df_15min = df_15min.reset_index()

df_15min

df_15min = df_15min.drop('index', axis = 'columns')
df_15min

z = pd.DataFrame({'LpDate':[20210319110000], 'inv_id':[210], 'inv_A':[55600.0], 'inv_set_freq':[627.2], 'inv_cur_freq':[894.8], 'inv_run_state':[19]})
z

z = z.set_index(pd.Index(['11787']))
z

df_15 = pd.concat([df_15min, z], axis=0)
df_15

df_15 = df_15.sort_values('LpDate')
df_15

df_15 = df_15.reset_index(drop = True)
df_15

a46133 = pd.DataFrame({'LpDate':[20210719135000], 'inv_id':['NaN'], 'inv_A':['NaN'], 'inv_set_freq':['NaN'], 'inv_cur_freq':['NaN'], 'inv_run_state':['NaN']})
a46133

a488 = pd.DataFrame({'LpDate':[ 
20210205135000,
20210205135500,
20210205140000,
20210205140500,
20210205141000,
20210205141500,
20210205142000,
20210205142500,
20210205143000,
20210205143500,
20210205144000,
20210205144500,
20210205145000,
20210205145500,
20210205150000], 
'inv_id':['NaN', 'NaN','NaN','NaN', 'NaN', 'NaN','NaN','NaN', 'NaN', 'NaN','NaN','NaN', 'NaN', 'NaN','NaN'],
'inv_A':['NaN', 'NaN','NaN','NaN', 'NaN', 'NaN','NaN','NaN', 'NaN', 'NaN','NaN','NaN', 'NaN', 'NaN','NaN'],
'inv_set_freq':['NaN', 'NaN','NaN','NaN', 'NaN', 'NaN','NaN','NaN', 'NaN', 'NaN','NaN','NaN', 'NaN', 'NaN','NaN'], 
'inv_cur_freq':['NaN', 'NaN','NaN','NaN', 'NaN', 'NaN','NaN','NaN', 'NaN', 'NaN','NaN','NaN', 'NaN', 'NaN','NaN'],
'inv_run_state':['NaN', 'NaN','NaN','NaN', 'NaN', 'NaN','NaN','NaN', 'NaN', 'NaN','NaN','NaN', 'NaN', 'NaN','NaN']})
a488
#16개

a1369 = pd.DataFrame({'LpDate':[20210319110000], 'inv_id':['NaN'], 'inv_A':['NaN'], 'inv_set_freq':['NaN'], 'inv_cur_freq':['NaN'], 'inv_run_state':['NaN']})
a1369

a12312 = pd.DataFrame({'LpDate':[20210319134500], 'inv_id':['NaN'], 'inv_A':['NaN'], 'inv_set_freq':['NaN'], 'inv_cur_freq':['NaN'], 'inv_run_state':['NaN']})
a12312

a35361= pd.DataFrame(
{'LpDate':[20210608142500,
20210608143500,
20210608144000,
20210608145000], 'inv_id':['NaN', 'NaN', 'NaN', 'NaN'], 'inv_A':['NaN', 'NaN', 'NaN', 'NaN'], 'inv_set_freq':['NaN', 'NaN', 'NaN', 'NaN'], 'inv_cur_freq':['NaN', 'NaN', 'NaN', 'NaN'], 'inv_run_state':['NaN', 'NaN', 'NaN', 'NaN']})
a35361

a35577 = pd.DataFrame({'LpDate':[20210609083500,
20210609084000,
20210609084500,
20210609085000], 'inv_id':['NaN', 'NaN','NaN','NaN'], 'inv_A':['NaN', 'NaN','NaN','NaN'], 'inv_set_freq':['NaN', 'NaN','NaN','NaN'], 'inv_cur_freq':['NaN', 'NaN','NaN','NaN'], 'inv_run_state':['NaN', 'NaN','NaN','NaN']})
a35577

a35754 = pd.DataFrame({'LpDate':[20210609223500], 'inv_id':['NaN'], 'inv_A':['NaN'], 'inv_set_freq':['NaN'], 'inv_cur_freq':['NaN'], 'inv_run_state':['NaN']})
a35754

a39063 = pd.DataFrame({'LpDate':[20210621112500, 20210621113000],
                       'inv_id':['NaN', 'NaN'], 'inv_A':['NaN', 'NaN'], 'inv_set_freq':['NaN', 'NaN'], 'inv_cur_freq':['NaN', 'NaN'], 'inv_run_state':['NaN', 'NaN']})
a39063

a52200 = pd.DataFrame({'LpDate':[20210903165000], 'inv_id':['NaN'], 'inv_A':['NaN'], 'inv_set_freq':['NaN'], 'inv_cur_freq':['NaN'], 'inv_run_state':['NaN']})
a52200

a76701 = pd.DataFrame({'LpDate':[20211130115500], 'inv_id':['NaN'], 'inv_A':['NaN'], 'inv_set_freq':['NaN'], 'inv_cur_freq':['NaN'], 'inv_run_state':['NaN']})
a76701

a114012 = pd.DataFrame({'LpDate':[20220409013000], 'inv_id':['NaN'], 'inv_A':['NaN'], 'inv_set_freq':['NaN'], 'inv_cur_freq':['NaN'], 'inv_run_state':['NaN']})
a114012

a127761 = pd.DataFrame({'LpDate':[20220526190500], 'inv_id':['NaN'], 'inv_A':['NaN'], 'inv_set_freq':['NaN'], 'inv_cur_freq':['NaN'], 'inv_run_state':['NaN']})
a127761

df_num = pd.merge(a488, a1369, how='outer')
df_num

df_num = pd.merge(df_num, a12312, how='outer')
df_num

df_num = pd.merge(df_num, a35361, how='outer')

df_num = pd.merge(df_num, a35577, how='outer')

df_num = pd.merge(df_num, a35754, how='outer')

df_num = pd.merge(df_num, a39063, how='outer')

df_num = pd.merge(df_num, a46133, how='outer')

df_num = pd.merge(df_num, a52200, how='outer')

df_num = pd.merge(df_num, a76701, how='outer')

df_num = pd.merge(df_num, a114012, how='outer')

df_num = pd.merge(df_num, a127761, how='outer')

df_num

df_num.info()

df_num['inv_id'] = df_num['inv_id'].apply(pd.to_numeric, errors = 'coerce')
df_num

df_num['inv_A'] = df_num['inv_A'].apply(pd.to_numeric, errors = 'coerce')

df_num['inv_set_freq'] = df_num['inv_set_freq'].apply(pd.to_numeric, errors = 'coerce')

df_num['inv_cur_freq'] = df_num['inv_cur_freq'].apply(pd.to_numeric, errors = 'coerce')

df_num['inv_run_state'] = df_num['inv_run_state'].apply(pd.to_numeric, errors = 'coerce')

df_num.info()

df_15min

# df_qqq = pd.merge(df_15, df_num, how='outer')
df_qqq = df_15
df_qqq

df_qqq = df_qqq[:-1]

df_qqq = df_qqq.sort_values(by=['LpDate'], ascending=[True])
df_qqq

df_qqq = df_qqq.reset_index(drop=True)
df_qqq

df_qqq = df_qqq.fillna(method='pad')
df_qqq

# df_qqq['LpDate'] = df_qqq['LpDate']//10000
# df_qqq

df_qqq = df_qqq.groupby('LpDate').agg({'LpDate':max, 'inv_id':sum, 'inv_A':sum, 'inv_set_freq':'mean', 'inv_cur_freq':'mean', 'inv_run_state':sum})
df_qqq

























a = pd.DataFrame(list(range(0, 57152)))
a

b = pd.DataFrame(list(range(0, 57152)))
b

c = pd.DataFrame(list(range(0, 57152)))
c

ab = pd.concat([a, b], axis=0)

ab

abc = ab = pd.concat([ab, c], axis=0)

abc

abc = abc.sort_values(by=abc.columns[0])
abc

abc.reset_index(inplace=True, drop=True)
abc

df_15['LpDate'].info()

df_abc = pd.concat([df_qqq, abc], axis = 1)
df_abc

df_abc['LpDate'].info()

df_abc = df_abc.groupby(0).agg({'LpDate':max, 'inv_id':sum, 'inv_A':sum, 'inv_set_freq':sum, 'inv_cur_freq':sum, 'inv_run_state':sum})
df_abc

df_abc['LpDate']

from datetime import datetime, timedelta

df_lp = pd.read_csv('/home/jovyan/aaaa/raw_kepcodaylpdata.csv')
df_lp

df_lp.info()

df_lp = df_lp[1:]
df_lp

df_lp = df_lp.reset_index(drop = True)
df_lp

df_lp['LpDate'] = df_lp['LpDate']//10000
df_lp

























df_end = pd.merge(df_abc, df_lp, how='outer')
df_end

# df_end.to_csv('./df_end.csv')

df_end = df_end[0:57152]
df_end

df_end.to_csv('./df_end.csv')



"""---"""





df_wma = pd.read_csv('/home/jovyan/aaaa/raw_wmahudata.csv')
df_wma

df_wma['ahu_id'] = df_wma['ahu_id'].replace(['A00', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06', 'A07', 'A08', 'A09', 'A10'], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
df_wma

df_wma = df_wma.sort_values(by=['run_datetime', 'ahu_id'])
df_wma

df_wma = df_wma.drop(labels=['data_id', 'ahu_set_temp', 'ahu_set_hum', 'ahu_ret_temp', 'ahu_ret_hum', 'ahu_sup_temp', 'ahu_sup_hum', 'ahu_comp1_run', 'ahu_comp2_run', 'ahu_warm_run', 'ahu_addhum_run', 'ahu_cool_diff', 'ahu_warm_diff', 'ahu_addhum_diff', 'ahu_rmvhum_diff'], axis=1)
df_wma

df_wm = df_wma[231:-11]
df_wm

1880196  /3

df_wm = df_wm.reset_index(drop=True)

aa = df_wm.copy()

df_wm.info()

a = [0,1,2,3,4,5,6,7,8,9,10]
for i in range(1880449):
    a.append(a[i])

import pandas as pd

# test = pd.DataFrame(a, columns=['0'])
# test.astype('object')

# test['0'] = test['0'].astype('object')

# tt = pd.concat([df_wm, test], axis=1)

# tt.dropna()

# tt.head(20)

# df_wma = df_wma[88:]
# df_wma

1880362 / 11

df_wm['ahu_id'].value_counts()

# tt.to_csv('./tt.csv')

# tt.info()

# tt['run_datetime']  = tt['run_datetime'].astype(int)

# tt['ahu_id'].value_counts()

df_wm = df_wm.groupby('run_datetime').mean()
df_wm

df_wm = df_wm.reset_index()

df_wm



df_wm['run_datetime'] = df_wm['run_datetime']//10000
df_wm

df_wm = df_wm.groupby('run_datetime').agg({'run_datetime':max, 'ahu_id':sum, 'ahu_out_temp':'mean', 'ahu_out_hum':'mean'})
df_wm

df_qqq



































170928/3

# qwe = pd.DataFrame({'run_datetime':[20220526190500], 'ahu_id':[5.0], 'ahu_out_temp':[18.7909091], 'ahu_out_hum':[39.872727]})
# qwe

# qwe = qwe.groupby('run_datetime').mean()
# qwe

# df_wm.loc[20221025100500] = ['5.0', '18.790909', '39.872727']

a0 = pd.DataFrame(list(range(0, 56976)))

a1 = pd.DataFrame(list(range(0, 56976)))

a2 = pd.DataFrame(list(range(0, 56976)))

170934/3



a01 = pd.concat([a0, a1], axis=0)

a12 = pd.concat([a01, a2], axis=0)

a12 = a12.sort_values(by=a12.columns[0])
a12

a12.reset_index(inplace=True, drop=True)



df_mmm = pd.concat([df_wm, a12], axis = 1)
df_mmm

df_mmm = df_mmm.groupby(0).agg({'run_datetime':max, 'ahu_id':sum, 'ahu_out_temp':sum, 'ahu_out_hum':sum})
df_mmm

df_mmm.rename(columns={'run_datetime':'LpDate'}, inplace=True)
df_mmm

# df_mmm.to_csv('./df_mmm.csv')

df_end

df_lp

df_wm

df_qqq

df_wm = df_wm.rename(columns={'run_datetime':'LpDate'})
df_wm

df_wm = df_wm.reset_index(drop=True)
df_wm

df_qqq = df_qqq.reset_index(drop=True)
df_qqq

df_lp = df_lp.groupby('LpDate').agg({'LpDate':max, 'LpID':sum, 'LpData':sum})
df_lp

df_lp = df_lp.reset_index(drop=True)
df_lp

df_wm df_qqq df_lp

df_gg = pd.merge(df_wm, df_qqq)

df_gg

df_gg = pd.merge(df_gg, df_lp)
df_gg

# Commented out IPython magic to ensure Python compatibility.
# %pwd

df_gg

df_g = df_gg.drop({'ahu_id', 'inv_id', 'LpID'}, axis = 'columns')
df_g



df_gg['inv_A'] = df_gg['inv_A']/12
df_gg

df_gg



# df_g.to_csv('./df_g.csv')

df_gg.to_csv('./df_g.csv')

